modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="billycool1"
version="1.0.0"
displayName="billycool"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="billy, MCreator"

[[dependencies.billycool1]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




